// Phase 2 — carrier master + client carrier binding errors.
// sys_code prefix 1400xxx (14: carrier domain, 0: internal error class).
export const CARRIER_ERROR = {
  CARRIER_CODE_DUPLICATED: {
    status: 400,
    sys_code: "1400001",
    message: "carrier_code already exists",
    zh_hk: "carrier_code 已存在",
    zh_cn: "carrier_code 已存在",
    en: "carrier_code already exists",
  },
  CARRIER_NOT_FOUND: {
    status: 404,
    sys_code: "1400002",
    message: "Carrier not found",
    zh_hk: "找不到該物流商",
    zh_cn: "找不到该物流商",
    en: "Carrier not found",
  },
  CARRIER_DISABLED: {
    status: 400,
    sys_code: "1400003",
    message: "Carrier is disabled",
    zh_hk: "該物流商已停用",
    zh_cn: "该物流商已停用",
    en: "Carrier is disabled",
  },
  OAUTH_CONFIG_REQUIRED: {
    status: 400,
    sys_code: "1400004",
    message: "oauth_config is required when auth_type=oauth",
    zh_hk: "OAuth 設定為必填",
    zh_cn: "OAuth 设定为必填",
    en: "oauth_config is required when auth_type=oauth",
  },
  CREDENTIALS_VALIDATION_FAILED: {
    status: 400,
    sys_code: "1400005",
    message: "Credentials failed validation against carrier rules",
    zh_hk: "認證資料未通過 carrier 規則驗證",
    zh_cn: "认证资料未通过 carrier 规则验证",
    en: "Credentials failed validation against carrier rules",
  },
  CARRIER_ACCOUNT_DUPLICATED: {
    status: 400,
    sys_code: "1400010",
    message: "You already have a carrier account with this nickname",
    zh_hk: "已存在同 carrier 同暱稱的帳號",
    zh_cn: "已存在同 carrier 同昵称的账号",
    en: "You already have a carrier account with this nickname",
  },
  CARRIER_ACCOUNT_NOT_FOUND: {
    status: 404,
    sys_code: "1400011",
    message: "Carrier account not found",
    zh_hk: "找不到此物流帳號",
    zh_cn: "找不到此物流账号",
    en: "Carrier account not found",
  },
  CARRIER_ACCOUNT_NOT_ACTIVE: {
    status: 400,
    sys_code: "1400012",
    message: "Carrier account is not active",
    zh_hk: "此物流帳號非啟用狀態",
    zh_cn: "此物流账号非启用状态",
    en: "Carrier account is not active",
  },
  // OAuth flow errors
  OAUTH_STATE_INVALID: {
    status: 400,
    sys_code: "1400020",
    message: "OAuth state token is invalid or expired",
    zh_hk: "OAuth 驗證狀態無效或已過期",
    zh_cn: "OAuth 验证状态无效或已过期",
    en: "OAuth state token is invalid or expired",
  },
  OAUTH_USER_DENIED: {
    status: 400,
    sys_code: "1400021",
    message: "User denied authorization",
    zh_hk: "您已取消授權",
    zh_cn: "您已取消授权",
    en: "User denied authorization",
  },
  OAUTH_TOKEN_EXCHANGE_FAILED: {
    status: 502,
    sys_code: "1400022",
    message: "Failed to exchange authorization code for token",
    zh_hk: "OAuth Token 交換失敗",
    zh_cn: "OAuth Token 交换失败",
    en: "Failed to exchange authorization code for token",
  },
};
