export const COMMON_ERROR = {
  INTERNAL_SERVER_ERROR: {
    status: 500,
    sys_code: "9900000", // 99: Common Error, 0: Internal Error, 0000: Error no
    message: "Internal Server Error",
    en: "Internal Server Error",
    zh_hk: "內部伺服器錯誤",
    zh_cn: "内部服务器错误",
  },
  UNAUTHORIZED: {
    status: 401,
    sys_code: "9900001",
    message: "Unauthorized",
    en: "Unauthorized",
    zh_hk: "未經授權",
    zh_cn: "未经授权",
  },
  INVALID_CREDENTIALS: {
    status: 401,
    sys_code: "9900002",
    message: "Invalid credentials",
    en: "Invalid credentials",
    zh_hk: "無效的憑證",
    zh_cn: "无效的凭证",
  },
  FORBIDDEN: {
    status: 403,
    sys_code: "9900003",
    message: "Forbidden",
    en: "Forbidden",
    zh_hk: "禁止",
    zh_cn: "禁止",
  },
  NOT_IMPLEMENTED: {
    status: 501,
    sys_code: "9900004",
    message: "Not Implemented",
    en: "Not Implemented",
    zh_hk: "未實現",
    zh_cn: "未实现",
  },
  MISSING_FIELD: {
    status: 400,
    sys_code: "9900005",
    message: "Missing Field: {field}",
    en: "Missing Field: {field}",
    zh_hk: "缺少字段: {field}",
    zh_cn: "缺少字段: {field}",
  },
  RECORD_DUPLICATE: {
    status: 400,
    sys_code: "9900006",
    message: "Record already exists: {key}",
    en: "Record already exists: {key}",
    zh_hk: "記錄已存在: {key}",
    zh_cn: "记录已存在: {key}",
  },
  INVALID_FIELD: {
    status: 400,
    sys_code: "9900008",
    message: "Invalid Field: {field}",
    en: "Invalid Field: {field}",
    zh_hk: "無效字段: {field}",
    zh_cn: "无效字段: {field}",
  },
  RECORD_NOT_FOUND: {
    status: 400,
    sys_code: "9900009",
    message: "Record not found",
    en: "Record not found",
    zh_hk: "找不到記錄",
    zh_cn: "找不到记录",
  },
  INVALID_WAREHOUSE: {
    status: 400,
    sys_code: "9900010", // 10: Common Error, 0: Internal Error, 0000: Error no
    message: "Invalid Warehouse Code: {code}",
    en: "Invalid Warehouse Code: {code}",
    zh_hk: "倉庫編號錯誤: {code}",
    zh_cn: "仓库编号错误: {code}",
  },
  EXIST_REF_NO: {
    status: 400,
    sys_code: "9900011",
    message: "Reference number already exists",
    en: "Reference number already exists",
    zh_hk: "參考編號已存在",
    zh_cn: "参考编号已存在",
  },
  REPEAT_REF_NO: {
    status: 400,
    sys_code: "9900012",
    message: "Duplicated reference number",
    en: "Duplicated reference number",
    zh_hk: "參考編號重複",
    zh_cn: "参考编号重复",
  },
  INVALID_RESTRICTION_KEY: {
    status: 400,
    sys_code: "9900013",
    message: "Invalid restriction tag: {code}",
    en: "Invalid restriction tag: {code}",
    zh_hk: "無效的限制代碼: {code}",
    zh_cn: "无效的限制代码: {code}",
  },
  INVALID_CATEGORY_KEY: {
    status: 400,
    sys_code: "9900014",
    message: "Invalid category: {code}",
    en: "Invalid category: {code}",
    zh_hk: "無效的類別代碼: {code}",
    zh_cn: "无效的类别代码: {code}",
  },
  MAX_VALUE_EXCEEDED: {
    status: 400,
    sys_code: "9900015",
    message: "[{key}] Max value exceeded: {value}",
    en: "[{key}] Max value exceeded: {value}",
    zh_hk: "[{key}] 超出最大值: {value}",
    zh_cn: "[{key}] 超出最大值: {value}",
  },
  MIN_VALUE_EXCEEDED: {
    status: 400,
    sys_code: "9900016",
    message: "[{key}] Min value exceeded: {value}",
    en: "[{key}] Min value exceeded: {value}",
    zh_hk: "[{key}] 超出最小值: {value}",
    zh_cn: "[{key}] 超出最小值: {value}",
  },
  MAX_LENGTH_EXCEEDED: {
    status: 400,
    sys_code: "9900015",
    message: "[{key}] Max {max} items can be added",
    en: "[{key}] Max {max} items can be added",
    zh_hk: "[{key}] 最多只能加入 {max} 個項目",
    zh_cn: "[{key}] 最多只能加入 {max} 个项目",
  },
  MIN_LENGTH_EXCEEDED: {
    status: 400,
    sys_code: "9900015",
    message: "[{key}] Min {min} items required",
    en: "[{key}] Min {min} items required",
    zh_hk: "[{key}] 最少保留 {min} 個項目",
    zh_cn: "[{key}] 最少保留 {min} 个项目",
  },
  MISSING_FORM_CONFIG: {
    status: 500,
    sys_code: "9900017",
    message: "[{key}] Missing Config: {attribute}",
    en: "[{key}] Missing Config: {attribute}",
    zh_hk: "[{key}] 欠缺配置: {attribute}",
    zh_cn: "[{key}] 欠缺配置: {attribute}",
  },
  INVALID_LOGISTIC_PARTY: {
    status: 400,
    sys_code: "9900018",
    message: "Invalid logistic platform: {code}",
    en: "Invalid logistic platform: {code}",
    zh_hk: "無效的物流平台: {code}",
    zh_cn: "无效的物流平台: {code}",
  },
};
