export const INBOUND_ERROR = {
  INBOUND_NOT_CANCELABLE: {
    status: 400,
    sys_code: "1100001", // 11: Inbound Error, 0: Internal Error, 0000: Error no
    message: "Inbound not cancelable",
    en: "That inbound order is not cancelable",
    zh_hk: "該入庫單處於不能取消的狀態",
    zh_cn: "该入库单处于不能取消的状态",
  },
  INVALID_INBOUND_STATUS: {
    status: 400,
    sys_code: "1100002",
    message: "Invalid Inbound Status: {status}",
    en: "Invalid Inbound Status: {status}",
    zh_hk: "無效的入庫狀態: {status}",
    zh_cn: "无效的入库状态: {status}",
  },
  ADDRESS_NOT_FOUND: {
    status: 400,
    sys_code: "1100002",
    message: "Address not found",
    en: "Address not found",
    zh_hk: "找不到地址",
    zh_cn: "找不到地址",
  },

  FAIL_TO_CREATE_OUTBOUND_ORDER: {
    status: 400,
    sys_code: "1100003",
    message: "Unable to create Orders: {error}",
    en: "Unable to create Orders: {error}",
    zh_hk: "無法生成出庫訂單: {error}",
    zh_cn: "无法生成出库订单: {error}",
  },

  MISSING_DECLARED_VALUE: {
    status: 400,
    sys_code: "1100004",
    message: "Missing Declared Value",
    en: "Missing Declared Value",
    zh_hk: "請輸入申報價值",
    zh_cn: "请输入申报价值",
  },

  MISSING_CATEGORY: {
    status: 400,
    sys_code: "1100005",
    message: "Missing Category",
    en: "Missing Category",
    zh_hk: "請選擇類別",
    zh_cn: "请选择类别",
  },

  // ── Phase 4 — inbound declaration ────────────────────────────
  DECLARED_ITEMS_REQUIRED: {
    status: 400,
    sys_code: "1100010",
    message: "At least one declared item is required",
    en: "At least one declared item is required",
    zh_hk: "至少需要 1 項申報品項",
    zh_cn: "至少需要 1 项申报品项",
  },
  TOO_MANY_DECLARED_ITEMS: {
    status: 400,
    sys_code: "1100011",
    message: "Too many declared items (max 50)",
    en: "Too many declared items (max 50)",
    zh_hk: "申報品項過多（上限 50）",
    zh_cn: "申报品项过多（上限 50）",
  },
  TRACKING_NO_DUPLICATED: {
    status: 400,
    sys_code: "1100012",
    message: "Tracking number already used for this carrier",
    en: "Tracking number already used for this carrier",
    zh_hk: "該物流商已有此追蹤號",
    zh_cn: "该物流商已有此追踪号",
  },
  INVALID_SUBCATEGORY: {
    status: 400,
    sys_code: "1100013",
    message: "Subcategory does not belong to the selected category",
    en: "Subcategory does not belong to the selected category",
    zh_hk: "子類別不屬於所選類別",
    zh_cn: "子类别不属于所选类别",
  },
  WAREHOUSE_NOT_FOUND: {
    status: 400,
    sys_code: "1100014",
    message: "Warehouse not found or disabled",
    en: "Warehouse not found or disabled",
    zh_hk: "找不到倉庫或已停用",
    zh_cn: "找不到仓库或已停用",
  },
  CARRIER_INBOUND_NOT_FOUND: {
    status: 400,
    sys_code: "1100015",
    message: "Inbound carrier not found or disabled",
    en: "Inbound carrier not found or disabled",
    zh_hk: "找不到入庫快遞商或已停用",
    zh_cn: "找不到入库快递商或已停用",
  },
  INVALID_CARRIER_ACCOUNT: {
    status: 400,
    sys_code: "1100016",
    message: "Carrier account does not belong to client or is inactive",
    en: "Carrier account does not belong to client or is inactive",
    zh_hk: "物流帳號不屬於您或未啟用",
    zh_cn: "物流账号不属于您或未启用",
  },
  SINGLE_SHIPPING_REQUIRED_FIELDS_MISSING: {
    status: 400,
    sys_code: "1100017",
    message:
      "shipping_destination requires receiver_address_snapshot + carrier_account_id (+ saved_address_id for managed_consign)",
    en: "Shipping destination requires recipient address and carrier account",
    zh_hk: "需要填寫收件地址與物流帳號（託管寄送另需地址簿 ID）",
    zh_cn: "需要填写收件地址与物流账号（托管寄送另需地址簿 ID）",
  },
  SHIPPING_INFO_NOT_ALLOWED_FOR_CONSOLIDATED: {
    status: 400,
    sys_code: "1100018",
    message:
      "shipping_destination must be empty when shipping_mode=manual_consolidate",
    en: "Shipping destination must be empty when shipping mode is manual consolidate",
    zh_hk: "手動併貨不可填寫收件資訊",
    zh_cn: "手动并货不可填写收件资讯",
  },
  INVALID_SAVED_ADDRESS: {
    status: 400,
    sys_code: "1100025",
    message: "Saved address does not belong to the client",
    en: "Saved address does not belong to the client",
    zh_hk: "地址簿項目不屬於您",
    zh_cn: "地址簿项目不属于您",
  },
  CONSOLIDATION_GROUP_NOT_FOUND: {
    status: 404,
    sys_code: "1100026",
    message: "Consolidation group not found",
    en: "Consolidation group not found",
    zh_hk: "找不到託管組",
    zh_cn: "找不到托管组",
  },
  CONSOLIDATION_GROUP_NOT_RELEASABLE: {
    status: 400,
    sys_code: "1100027",
    message: "Consolidation group is no longer pending and cannot be released",
    en: "Consolidation group is no longer pending and cannot be released",
    zh_hk: "託管組已不在 pending 狀態，無法立即排出庫",
    zh_cn: "托管组已不在 pending 状态，无法立即排出库",
  },
  CANNOT_EDIT_AFTER_ARRIVED: {
    status: 400,
    sys_code: "1100019",
    message: "Cannot edit inbound after it has arrived at the warehouse",
    en: "Cannot edit inbound after it has arrived at the warehouse",
    zh_hk: "貨物已到倉，無法修改預報",
    zh_cn: "货物已到仓，无法修改预报",
  },
  CANNOT_CANCEL_AFTER_ARRIVED: {
    status: 400,
    sys_code: "1100020",
    message: "Cannot cancel inbound after it has arrived",
    en: "Cannot cancel inbound after it has arrived",
    zh_hk: "貨物已到倉，無法取消",
    zh_cn: "货物已到仓，无法取消",
  },
  CANNOT_ABANDON_AFTER_PICKING: {
    status: 400,
    sys_code: "1100021",
    message: "Cannot abandon inbound after picking has started",
    en: "Cannot abandon inbound after picking has started",
    zh_hk: "已開始揀貨，無法廢棄",
    zh_cn: "已开始拣货，无法废弃",
  },
  ABANDON_CONFIRMATION_MISMATCH: {
    status: 400,
    sys_code: "1100022",
    message: "Confirmation text must be exactly '廢棄'",
    en: "Confirmation text must be exactly '廢棄'",
    zh_hk: "請輸入「廢棄」二字以確認",
    zh_cn: "请输入「廢棄」二字以确认",
  },
  INBOUND_NOT_FOUND: {
    status: 404,
    sys_code: "1100023",
    message: "Inbound not found",
    en: "Inbound not found",
    zh_hk: "找不到預報單",
    zh_cn: "找不到预报单",
  },
  CANNOT_CHANGE_METHOD_AFTER_ARRIVED: {
    status: 400,
    sys_code: "1100040",
    message: "Cannot change shipping method after the inbound has arrived",
    en: "Cannot change shipping method after the inbound has arrived",
    zh_hk: "貨物已到倉，無法再改寄送方式",
    zh_cn: "货物已到仓，无法再改寄送方式",
  },
  SAME_SHIPPING_MODE: {
    status: 400,
    sys_code: "1100041",
    message: "Shipping mode is already set to the requested value",
    en: "Shipping mode is already set to the requested value",
    zh_hk: "寄送方式無變化",
    zh_cn: "寄送方式无变化",
  },
  MANAGED_REQUIRES_ADDRESS_AND_CARRIER: {
    status: 400,
    sys_code: "1100042",
    message: "Managed shipping requires saved_address_id and carrier_account_id",
    en: "Managed shipping requires saved_address_id and carrier_account_id",
    zh_hk: "託管寄送必須提供已儲存地址與 Carrier 帳號",
    zh_cn: "托管寄送必须提供已存储地址与 Carrier 账号",
  },
  DAILY_COUNTER_EXCEEDED: {
    status: 500,
    sys_code: "1100024",
    message: "Daily counter exceeded — please contact support",
    en: "Daily counter exceeded — please contact support",
    zh_hk: "每日序號超出，請聯絡客服",
    zh_cn: "每日序号超出，请联系客服",
  },
  WORKING_CALENDAR_INVALID_DATE: {
    status: 400,
    sys_code: "1100028",
    message: "Date must be a valid YYYY-MM-DD value",
    en: "Date must be a valid YYYY-MM-DD value",
    zh_hk: "日期格式必須為 YYYY-MM-DD 且為有效日期",
    zh_cn: "日期格式必须为 YYYY-MM-DD 且为有效日期",
  },
  WORKING_CALENDAR_INVALID_TYPE: {
    status: 400,
    sys_code: "1100029",
    message: "Type must be holiday or non_working",
    en: "Type must be holiday or non_working",
    zh_hk: "類型必須為 holiday 或 non_working",
    zh_cn: "类型必须为 holiday 或 non_working",
  },
  WORKING_CALENDAR_WAREHOUSE_REQUIRED: {
    status: 400,
    sys_code: "1100030",
    message: "Warehouse code is required",
    en: "Warehouse code is required",
    zh_hk: "必須指定倉庫",
    zh_cn: "必须指定仓库",
  },
  WORKING_CALENDAR_ENTRY_NOT_FOUND: {
    status: 404,
    sys_code: "1100031",
    message: "Working calendar entry not found",
    en: "Working calendar entry not found",
    zh_hk: "找不到該工作日項目",
    zh_cn: "找不到该工作日项目",
  },
  CONSOLIDATION_RELEASE_INBOUND_NOT_IN_GROUP: {
    status: 400,
    sys_code: "1100032",
    message: "One or more selected inbounds do not belong to this group",
    en: "One or more selected inbounds do not belong to this group",
    zh_hk: "選中的預報不屬於此託管組",
    zh_cn: "选中的预报不属于此托管组",
  },
  CONSOLIDATION_RELEASE_INBOUND_NOT_SHELVED: {
    status: 400,
    sys_code: "1100033",
    message: "One or more selected inbounds have not been shelved yet",
    en: "One or more selected inbounds have not been shelved yet",
    zh_hk: "選中的預報尚未完成上架，無法立即出庫",
    zh_cn: "选中的预报尚未完成上架，无法立即出库",
  },
};
