export const INBOUND_ERROR = {
  INBOUND_NOT_CANCELABLE: {
    status: 400,
    sys_code: "1100001", // 11: Inbound Error, 0: Internal Error, 0000: Error no
    message: "Inbound not cancelable",
    en: "That inbound order is not cancelable",
    zh_hk: "該入庫單處於不能取消的狀態",
    zh_cn: "该入库单处于不能取消的状态",
  },
  INVALID_INBOUND_STATUS: {
    status: 400,
    sys_code: "1100002",
    message: "Invalid Inbound Status: {status}",
    en: "Invalid Inbound Status: {status}",
    zh_hk: "無效的入庫狀態: {status}",
    zh_cn: "无效的入库状态: {status}",
  },
  ADDRESS_NOT_FOUND: {
    status: 400,
    sys_code: "1100002",
    message: "Address not found",
    en: "Address not found",
    zh_hk: "找不到地址",
    zh_cn: "找不到地址",
  },

  FAIL_TO_CREATE_OUTBOUND_ORDER: {
    status: 400,
    sys_code: "1100003",
    message: "Unable to create Orders: {error}",
    en: "Unable to create Orders: {error}",
    zh_hk: "無法生成出庫訂單: {error}",
    zh_cn: "无法生成出库订单: {error}",
  },

  MISSING_DECLARED_VALUE: {
    status: 400,
    sys_code: "1100004",
    message: "Missing Declared Value",
    en: "Missing Declared Value",
    zh_hk: "請輸入申報價值",
    zh_cn: "请输入申报价值",
  },

  MISSING_CATEGORY: {
    status: 400,
    sys_code: "1100005",
    message: "Missing Category",
    en: "Missing Category",
    zh_hk: "請選擇類別",
    zh_cn: "请选择类别",
  },

  // ── Phase 4 — inbound declaration ────────────────────────────
  DECLARED_ITEMS_REQUIRED: {
    status: 400,
    sys_code: "1100010",
    message: "At least one declared item is required",
    en: "At least one declared item is required",
    zh_hk: "至少需要 1 項申報品項",
    zh_cn: "至少需要 1 项申报品项",
  },
  TOO_MANY_DECLARED_ITEMS: {
    status: 400,
    sys_code: "1100011",
    message: "Too many declared items (max 50)",
    en: "Too many declared items (max 50)",
    zh_hk: "申報品項過多（上限 50）",
    zh_cn: "申报品项过多（上限 50）",
  },
  TRACKING_NO_DUPLICATED: {
    status: 400,
    sys_code: "1100012",
    message: "Tracking number already used for this carrier",
    en: "Tracking number already used for this carrier",
    zh_hk: "該物流商已有此追蹤號",
    zh_cn: "该物流商已有此追踪号",
  },
  INVALID_SUBCATEGORY: {
    status: 400,
    sys_code: "1100013",
    message: "Subcategory does not belong to the selected category",
    en: "Subcategory does not belong to the selected category",
    zh_hk: "子類別不屬於所選類別",
    zh_cn: "子类别不属于所选类别",
  },
  WAREHOUSE_NOT_FOUND: {
    status: 400,
    sys_code: "1100014",
    message: "Warehouse not found or disabled",
    en: "Warehouse not found or disabled",
    zh_hk: "找不到倉庫或已停用",
    zh_cn: "找不到仓库或已停用",
  },
  CARRIER_INBOUND_NOT_FOUND: {
    status: 400,
    sys_code: "1100015",
    message: "Inbound carrier not found or disabled",
    en: "Inbound carrier not found or disabled",
    zh_hk: "找不到入庫快遞商或已停用",
    zh_cn: "找不到入库快递商或已停用",
  },
  INVALID_CARRIER_ACCOUNT: {
    status: 400,
    sys_code: "1100016",
    message: "Carrier account does not belong to client or is inactive",
    en: "Carrier account does not belong to client or is inactive",
    zh_hk: "物流帳號不屬於您或未啟用",
    zh_cn: "物流账号不属于您或未启用",
  },
  SINGLE_SHIPPING_REQUIRED_FIELDS_MISSING: {
    status: 400,
    sys_code: "1100017",
    message:
      "single shipping requires receiver_address + carrier_account_id",
    en: "single shipping requires receiver_address + carrier_account_id",
    zh_hk: "單一寄送需要填寫收件地址與物流帳號",
    zh_cn: "单一寄送需要填写收件地址与物流账号",
  },
  SHIPPING_INFO_NOT_ALLOWED_FOR_CONSOLIDATED: {
    status: 400,
    sys_code: "1100018",
    message: "single_shipping must be empty when shipment_type=consolidated",
    en: "single_shipping must be empty when shipment_type=consolidated",
    zh_hk: "合併寄送不可填寫單一寄送資訊",
    zh_cn: "合并寄送不可填写单一寄送资讯",
  },
  CANNOT_EDIT_AFTER_ARRIVED: {
    status: 400,
    sys_code: "1100019",
    message: "Cannot edit inbound after it has arrived at the warehouse",
    en: "Cannot edit inbound after it has arrived at the warehouse",
    zh_hk: "貨物已到倉，無法修改預報",
    zh_cn: "货物已到仓，无法修改预报",
  },
  CANNOT_CANCEL_AFTER_ARRIVED: {
    status: 400,
    sys_code: "1100020",
    message: "Cannot cancel inbound after it has arrived",
    en: "Cannot cancel inbound after it has arrived",
    zh_hk: "貨物已到倉，無法取消",
    zh_cn: "货物已到仓，无法取消",
  },
  CANNOT_ABANDON_AFTER_PICKING: {
    status: 400,
    sys_code: "1100021",
    message: "Cannot abandon inbound after picking has started",
    en: "Cannot abandon inbound after picking has started",
    zh_hk: "已開始揀貨，無法廢棄",
    zh_cn: "已开始拣货，无法废弃",
  },
  ABANDON_CONFIRMATION_MISMATCH: {
    status: 400,
    sys_code: "1100022",
    message: "Confirmation text must be exactly '廢棄'",
    en: "Confirmation text must be exactly '廢棄'",
    zh_hk: "請輸入「廢棄」二字以確認",
    zh_cn: "请输入「廢棄」二字以确认",
  },
  INBOUND_NOT_FOUND: {
    status: 404,
    sys_code: "1100023",
    message: "Inbound not found",
    en: "Inbound not found",
    zh_hk: "找不到預報單",
    zh_cn: "找不到预报单",
  },
  DAILY_COUNTER_EXCEEDED: {
    status: 500,
    sys_code: "1100024",
    message: "Daily counter exceeded — please contact support",
    en: "Daily counter exceeded — please contact support",
    zh_hk: "每日序號超出，請聯絡客服",
    zh_cn: "每日序号超出，请联系客服",
  },
};
