export const OUTBOUND_ERROR = {
  NO_INBOUND_SELECTED: {
    sys_code: "1200001", // 12: Outbound Error, 0: Internal Error, 0001: Error no
    status: 400,
    message: "Please select at least {n} inbound order",
    en: "Please select at least {n} inbound order",
    zh_hk: "請選擇至少{n}張入庫訂單",
    zh_cn: "请选择至少{n}个入库订单",
  },
  MULTIPLE_WAREHOUSE_CODE_SELECTED: {
    sys_code: "1200002",
    status: 400,
    message: "Please select order from {n} warehouse",
    en: "Please select order from {n} warehouse",
    zh_hk: "請只選擇來自{n}個倉庫的入庫訂單",
    zh_cn: "请只选择来自{n}个仓库的入库订单",
  },
  REPEAT_INBOUND_ID: {
    sys_code: "1200003",
    status: 400,
    message: "Inbound Request is repeated: {inboundIds}",
    en: "Inbound Request is repeated: {inboundIds}",
    zh_hk: "入庫訂單重複: {inboundIds}",
    zh_cn: "入库订单重复: {inboundIds}",
  },
  MISSING_INBOUND_ID: {
    sys_code: "1200004",
    status: 400,
    message: "Missing Inbound ID: {keys}",
    en: "Missing Inbound ID: {keys}",
    zh_hk: "請輸入入庫單號: {keys}",
    zh_cn: "请输入入库单号: {keys}",
  },
  INBOUND_NOT_FOUND: {
    sys_code: "1200005",
    status: 400,
    message: "Inbound Request not found: {inboundIds}",
    en: "Inbound Request not found: {inboundIds}",
    zh_hk: "找不到入庫訂單號碼: {inboundIds}",
    zh_cn: "找不到入库订单号码: {inboundIds}",
  },
  INBOUND_NOT_OUTBOUNDABLE: {
    sys_code: "1200006",
    status: 400,
    message: "Non-outboundable Inbound found: {inboundIds}",
    en: "Non-outboundable Inbound found: {inboundIds}",
    zh_hk: "存在不能進行出庫操作的入庫訂單: {inboundIds}",
    zh_cn: "存在不能进行出库操作的入库订单: {inboundIds}",
  },
  INVALID_OUTBOUND_STATUS: {
    sys_code: "1200007",
    status: 400,
    message: "Invalid Outbound Status: {status}",
    en: "Invalid Outbound Status: {status}",
    zh_hk: "無效的出庫狀態: {status}",
    zh_cn: "无效的出库状态: {status}",
  },
  OUTBOUND_NOT_FOUND: {
    sys_code: "1200008",
    status: 400,
    message: "Outbound Request not found: {orderId}",
    en: "Outbound Request not found: {orderId}",
    zh_hk: "找不到出庫訂單: {orderId}",
    zh_cn: "找不到出库订单: {orderId}",
  },
  INVALID_YUN_COUNTRY_CODE: {
    sys_code: "1200009",
    status: 500,
    message: "Invalid Yun Express country code: {code}",
    en: "Invalid Yun Express country code: {code}",
    zh_hk: "錯誤的 Yun Express API 國家代碼: {code}",
    zh_cn: "错误的Yun Express API 国家代码: {code}",
  },
};
