// Phase 8 — WMS outbound flow errors. sys_code prefix 1800xxx.
// Kept separate from P7 OUTBOUND_CREATION_ERROR (slot 17) so wms-specific
// codes don't collide.
export const OUTBOUND_WMS_ERROR = {
  // ── pick stage ─────────────────────────────────────────────
  OUTBOUND_NOT_AVAILABLE_FOR_PICK: {
    status: 400,
    sys_code: "1800001",
    message: "Outbound is not available for pick: {status}",
    en: "Outbound is not available for pick: {status}",
    zh_hk: "出庫單 {status} 狀態下無法揀貨",
    zh_cn: "出库单 {status} 状态下无法拣货",
  },
  INBOUND_NOT_IN_OUTBOUND: {
    status: 400,
    sys_code: "1800002",
    message: "Inbound {inboundId} does not belong to outbound {outboundId}",
    en: "Inbound {inboundId} does not belong to outbound {outboundId}",
    zh_hk: "入庫單 {inboundId} 不在出庫單 {outboundId} 內",
    zh_cn: "入库单 {inboundId} 不在出库单 {outboundId} 内",
  },
  INBOUND_ALREADY_PICKED: {
    status: 400,
    sys_code: "1800003",
    message: "Inbound is already picked: {inboundIds}",
    en: "Inbound is already picked: {inboundIds}",
    zh_hk: "入庫單已揀過: {inboundIds}",
    zh_cn: "入库单已拣过: {inboundIds}",
  },
  LOCATION_MISMATCH: {
    status: 400,
    sys_code: "1800004",
    message: "Location mismatch: scanned {scanned}, expected {expected}",
    en: "Location mismatch: scanned {scanned}, expected {expected}",
    zh_hk: "庫位不符：掃描 {scanned}，預期 {expected}",
    zh_cn: "库位不符：扫描 {scanned}，预期 {expected}",
  },

  // ── pack stage ─────────────────────────────────────────────
  OUTBOUND_NOT_AVAILABLE_FOR_PACK: {
    status: 400,
    sys_code: "1800010",
    message: "Outbound is not available for pack: {status}",
    en: "Outbound is not available for pack: {status}",
    zh_hk: "出庫單 {status} 狀態下無法裝箱",
    zh_cn: "出库单 {status} 状态下无法装箱",
  },
  INBOUND_NOT_PICKED: {
    status: 400,
    sys_code: "1800011",
    message: "Inbound must be picked before pack: {inboundIds}",
    en: "Inbound must be picked before pack: {inboundIds}",
    zh_hk: "入庫單需先揀貨才可裝箱: {inboundIds}",
    zh_cn: "入库单需先拣货才可装箱: {inboundIds}",
  },
  INBOUND_ALREADY_BOXED: {
    status: 400,
    sys_code: "1800012",
    message: "Inbound is already boxed: {inboundIds}",
    en: "Inbound is already boxed: {inboundIds}",
    zh_hk: "入庫單已裝進其他箱: {inboundIds}",
    zh_cn: "入库单已装进其他箱: {inboundIds}",
  },
  NOT_ALL_INBOUNDS_BOXED: {
    status: 400,
    sys_code: "1800013",
    message: "Not all inbounds are boxed yet",
    en: "Not all inbounds are boxed yet",
    zh_hk: "仍有入庫單未裝進任何箱",
    zh_cn: "仍有入库单未装进任何箱",
  },
  EMPTY_BOX_INBOUND_LIST: {
    status: 400,
    sys_code: "1800014",
    message: "Box must contain at least one inbound",
    en: "Box must contain at least one inbound",
    zh_hk: "每箱至少需裝一張入庫單",
    zh_cn: "每箱至少需装一张入库单",
  },

  // ── weigh stage ────────────────────────────────────────────
  OUTBOUND_NOT_AVAILABLE_FOR_WEIGH: {
    status: 400,
    sys_code: "1800020",
    message: "Outbound is not available for weigh: {status}",
    en: "Outbound is not available for weigh: {status}",
    zh_hk: "出庫單 {status} 狀態下無法複重",
    zh_cn: "出库单 {status} 状态下无法复重",
  },
  BOX_NOT_FOUND: {
    status: 404,
    sys_code: "1800021",
    message: "Box not found: {boxNo}",
    en: "Box not found: {boxNo}",
    zh_hk: "找不到箱號 {boxNo}",
    zh_cn: "找不到箱号 {boxNo}",
  },
  BOX_NOT_AVAILABLE_FOR_WEIGH: {
    status: 400,
    sys_code: "1800022",
    message: "Box is not available for weigh: {status}",
    en: "Box is not available for weigh: {status}",
    zh_hk: "箱 {status} 狀態下無法複重",
    zh_cn: "箱 {status} 状态下无法复重",
  },
  BOX_COUNT_MISMATCH: {
    status: 400,
    sys_code: "1800023",
    message:
      "Box count mismatch: weighed {weighed}, registered {registered}",
    en: "Box count mismatch: weighed {weighed}, registered {registered}",
    zh_hk: "箱數對不上：量了 {weighed}，登記 {registered}",
    zh_cn: "箱数对不上：量了 {weighed}，登记 {registered}",
  },
  WEIGHT_TOLERANCE_EXCEEDED_NO_OVERRIDE: {
    status: 400,
    sys_code: "1800024",
    message:
      "Weight difference {diff}kg exceeds tolerance {tol}kg; override required",
    en: "Weight difference {diff}kg exceeds tolerance {tol}kg; override required",
    zh_hk: "重量差 {diff}kg 超過容差 {tol}kg，需員工確認 override",
    zh_cn: "重量差 {diff}kg 超过容差 {tol}kg，需员工确认 override",
  },

  // ── label stage ────────────────────────────────────────────
  OUTBOUND_NOT_AVAILABLE_FOR_LABEL: {
    status: 400,
    sys_code: "1800030",
    message: "Outbound is not available for label: {status}",
    en: "Outbound is not available for label: {status}",
    zh_hk: "出庫單 {status} 狀態下無法取運單",
    zh_cn: "出库单 {status} 状态下无法取运单",
  },
  OUTBOUND_NOT_AVAILABLE_FOR_PRINT: {
    status: 400,
    sys_code: "1800031",
    message: "Outbound is not available for label print: {status}",
    en: "Outbound is not available for label print: {status}",
    zh_hk: "出庫單 {status} 狀態下無法列印面單",
    zh_cn: "出库单 {status} 状态下无法列印面单",
  },

  // ── depart stage ───────────────────────────────────────────
  BOX_NOT_AVAILABLE_FOR_DEPART: {
    status: 400,
    sys_code: "1800040",
    message: "Box is not available for depart: {status}",
    en: "Box is not available for depart: {status}",
    zh_hk: "箱 {status} 狀態下無法離倉",
    zh_cn: "箱 {status} 状态下无法离仓",
  },
  BOX_ALREADY_DEPARTED: {
    status: 400,
    sys_code: "1800041",
    message: "Box has already departed",
    en: "Box has already departed",
    zh_hk: "此箱已離倉",
    zh_cn: "此箱已离仓",
  },

  // ── item-driven packing (P11) ──────────────────────────────
  ITEM_NOT_FOUND: {
    status: 400,
    sys_code: "1800050",
    message: "Item not found",
    en: "Item not found: {trackingNo}",
    zh_hk: "找不到此貨件: {trackingNo}",
    zh_cn: "找不到此货件: {trackingNo}",
  },
  ITEM_NOT_PACK_READY: {
    status: 400,
    sys_code: "1800051",
    message: "Item not ready for packing",
    en: "Item not picked yet: {trackingNo}",
    zh_hk: "此貨件未完成揀貨: {trackingNo}",
    zh_cn: "此货件未完成拣货: {trackingNo}",
  },
  PACK_BOX_NOT_FOUND: {
    status: 400,
    sys_code: "1800052",
    message: "Pack box not found",
    en: "Pack box not found: {boxNo}",
    zh_hk: "找不到此箱: {boxNo}",
    zh_cn: "找不到此箱: {boxNo}",
  },
  PACK_BOX_FULL: {
    status: 400,
    sys_code: "1800053",
    message: "Pack box already full",
    en: "{boxNo} is full",
    zh_hk: "{boxNo} 已滿",
    zh_cn: "{boxNo} 已满",
  },
  PACK_BOX_CLIENT_MISMATCH: {
    status: 400,
    sys_code: "1800054",
    message: "Box belongs to a different client",
    en: "{boxNo} belongs to a different client",
    zh_hk: "{boxNo} 屬於其他客戶，不可放入此貨件",
    zh_cn: "{boxNo} 属于其他客户，不可放入此货件",
  },
  PACK_BOX_NOT_OPEN: {
    status: 400,
    sys_code: "1800055",
    message: "Pack box not in open status",
    en: "{boxNo} is not open",
    zh_hk: "{boxNo} 不是開啟狀態",
    zh_cn: "{boxNo} 不是打开状态",
  },
  PACK_SINGLE_DIRECT_NO_MIX: {
    status: 400,
    sys_code: "1800056",
    message: "Single-direct box cannot accept other items",
    en: "Single direct shipment cannot be mixed with other items",
    zh_hk: "直發箱不可拼入其他貨件",
    zh_cn: "直发箱不可拼入其他货件",
  },
  PACK_SAME_BOX_NO_OP: {
    status: 400,
    sys_code: "1800057",
    message: "Item already in this box",
    en: "Item already in this box",
    zh_hk: "貨件已在此箱內",
    zh_cn: "货件已在此箱内",
  },
  PACK_CLIENT_NOT_FOUND: {
    status: 400,
    sys_code: "1800058",
    message: "Client not found",
    en: "Client not found",
    zh_hk: "客戶不存在",
    zh_cn: "客户不存在",
  },

  // ── 秤重置板 (weigh + palletize) — P12 (1800060+) ──────────
  PACK_BOX_NOT_SEALED: {
    status: 400,
    sys_code: "1800060",
    message: "Box is not sealed yet",
    en: "Box {boxNo} is not sealed yet",
    zh_hk: "{boxNo} 尚未封箱，無法秤重或置板",
    zh_cn: "{boxNo} 尚未封箱，无法称重或置板",
  },
  PACK_OUTBOUND_NOT_WEIGHT_VERIFIED: {
    status: 400,
    sys_code: "1800061",
    message: "Outbound is not ready for palletize",
    en: "Outbound {orderId} not ready for palletize (status: {status})",
    zh_hk: "出庫單 {orderId} 尚未完成秤重（目前狀態：{status}），無法置板",
    zh_cn: "出库单 {orderId} 尚未完成称重（当前状态：{status}），无法置板",
  },
  PACK_SESSION_BUSY: {
    status: 409,
    sys_code: "1800062",
    message: "Another palletize session in progress",
    en: "Palletize session locked by {staff} on outbound {outboundId}",
    zh_hk: "另一位員工 {staff} 正在置板出庫單 {outboundId}，請稍候",
    zh_cn: "另一位员工 {staff} 正在置板出库单 {outboundId}，请稍候",
  },
  PACK_PALLETIZE_WRONG_OUTBOUND: {
    status: 400,
    sys_code: "1800063",
    message: "Box does not belong to the locked outbound",
    en: "Session locked to {locked}; scanned box belongs to {scanned}",
    zh_hk: "目前已鎖定出庫單 {locked}，掃到的箱屬於 {scanned}，請先完成或取消當前置板",
    zh_cn: "当前已锁定出库单 {locked}，扫到的箱属于 {scanned}，请先完成或取消当前置板",
  },
  PACK_NO_ACTIVE_SESSION: {
    status: 400,
    sys_code: "1800064",
    message: "No active palletize session",
    en: "No active palletize session",
    zh_hk: "目前沒有進行中的置板",
    zh_cn: "当前没有进行中的置板",
  },
  PACK_PALLETIZE_INCOMPLETE: {
    status: 400,
    sys_code: "1800065",
    message: "Not all boxes scanned yet",
    en: "{missing} of {total} boxes not scanned yet",
    zh_hk: "仍有 {missing} / {total} 箱未掃描確認",
    zh_cn: "仍有 {missing} / {total} 箱未扫描确认",
  },
  WEIGHT_DIFF_OVER_TOLERANCE: {
    status: 400,
    sys_code: "1800066",
    message: "Weight difference exceeds tolerance",
    en: "Weight {actual}kg differs from expected {expected}kg by {diff}kg (> {tol}kg). Please re-check the box.",
    zh_hk: "實秤 {actual}kg 與預期 {expected}kg 相差 {diff}kg（超出 {tol}kg 容差）。請再三檢查箱內貨件及秤重",
    zh_cn: "实秤 {actual}kg 与预期 {expected}kg 相差 {diff}kg（超出 {tol}kg 容差）。请再三检查箱内货件及称重",
  },
};
