// Phase 5 — WMS scan errors. sys_code prefix 1500xxx.
export const SCAN_ERROR = {
  LOCATION_NOT_FOUND: {
    status: 400,
    sys_code: "1500001",
    message: "Location not found",
    en: "Location not found",
    zh_hk: "找不到此庫位",
    zh_cn: "找不到此库位",
  },
  LOCATION_MISMATCH: {
    status: 400,
    sys_code: "1500002",
    message: "Scanned location does not match item location",
    en: "Scanned location does not match item location",
    zh_hk: "掃描的庫位與貨物實際位置不符",
    zh_cn: "扫描的库位与货物实际位置不符",
  },
  BARCODE_PHOTO_REQUIRED: {
    status: 400,
    sys_code: "1500003",
    message: "Barcode photo is required",
    en: "Barcode photo is required",
    zh_hk: "請拍 barcode 條碼面",
    zh_cn: "请拍 barcode 条码面",
  },
  PACKAGE_PHOTO_REQUIRED: {
    status: 400,
    sys_code: "1500004",
    message: "Package photo is required",
    en: "Package photo is required",
    zh_hk: "請拍包裹外觀",
    zh_cn: "请拍包裹外观",
  },
  INVALID_STATUS_FOR_ARRIVE: {
    status: 400,
    sys_code: "1500005",
    message: "Inbound is not in a state to arrive",
    en: "Inbound is not in a state to arrive",
    zh_hk: "此預報目前狀態無法簽收",
    zh_cn: "此预报目前状态无法签收",
  },
  ALREADY_RECEIVED: {
    status: 400,
    sys_code: "1500006",
    message: "Inbound is already received",
    en: "Inbound is already received",
    zh_hk: "此預報已上架",
    zh_cn: "此预报已上架",
  },
  INBOUND_CANCELLED: {
    status: 400,
    sys_code: "1500007",
    message: "Inbound is cancelled",
    en: "Inbound is cancelled",
    zh_hk: "此預報已被客戶取消",
    zh_cn: "此预报已被客户取消",
  },
  INBOUND_ABANDONED: {
    status: 400,
    sys_code: "1500008",
    message: "Inbound is abandoned, place in exception area",
    en: "Inbound is abandoned, place in exception area",
    zh_hk: "此貨物已廢棄，請放異常處理區",
    zh_cn: "此货物已废弃，请放异常处理区",
  },
  UNCLAIMED_DUPLICATED: {
    status: 400,
    sys_code: "1500009",
    message: "Same tracking already registered as unclaimed",
    en: "Same tracking already registered as unclaimed",
    zh_hk: "此追蹤號已登記為無頭件",
    zh_cn: "此追踪号已登记为无头件",
  },
  UNDO_WINDOW_EXPIRED: {
    status: 400,
    sys_code: "1500010",
    message: "Undo window expired",
    en: "Undo window expired",
    zh_hk: "撤銷時間已過，請改由 admin 後台處理",
    zh_cn: "撤销时间已过，请改由 admin 后台处理",
  },
  CANNOT_UNDO_RECEIVED: {
    status: 400,
    sys_code: "1500011",
    message: "Cannot undo arrive after received",
    en: "Cannot undo arrive after received",
    zh_hk: "貨物已上架，無法撤銷簽收",
    zh_cn: "货物已上架，无法撤销签收",
  },
  ANOMALY_PHOTO_REQUIRED: {
    status: 400,
    sys_code: "1500012",
    message: "Anomaly photo is required",
    en: "Anomaly photo is required",
    zh_hk: "請拍異常照片",
    zh_cn: "请拍异常照片",
  },
  TOO_MANY_PHOTOS: {
    status: 400,
    sys_code: "1500013",
    message: "Too many photos",
    en: "Too many photos",
    zh_hk: "照片數量超過上限",
    zh_cn: "照片数量超过上限",
  },
  PHOTO_TOO_LARGE: {
    status: 400,
    sys_code: "1500014",
    message: "Photo exceeds size limit",
    en: "Photo exceeds size limit",
    zh_hk: "照片超過大小限制",
    zh_cn: "照片超过大小限制",
  },
  INVALID_PHOTO_TYPE: {
    status: 400,
    sys_code: "1500015",
    message: "Invalid photo type",
    en: "Invalid photo type",
    zh_hk: "不允許的照片類型",
    zh_cn: "不允许的照片类型",
  },
};
