// Phase 6 — unclaimed processing errors. sys_code prefix 1600xxx.
export const UNCLAIMED_ERROR = {
  UNCLAIMED_NOT_AVAILABLE: {
    status: 400,
    sys_code: "1600001",
    message: "Unclaimed shipment is no longer available",
    en: "Unclaimed shipment is no longer available",
    zh_hk: "此無頭件已被處理，無法操作",
    zh_cn: "此无头件已被处理，无法操作",
  },
  UNCLAIMED_NOT_AVAILABLE_FOR_CLIENT: {
    status: 400,
    sys_code: "1600002",
    message: "Unclaimed shipment is not assigned to this client",
    en: "Unclaimed shipment is not assigned to this client",
    zh_hk: "此無頭件並非指派給您",
    zh_cn: "此无头件并非指派给您",
  },
  PREVIOUSLY_REJECTED_BY_CLIENT: {
    status: 400,
    sys_code: "1600003",
    message: "Client previously rejected this shipment",
    en: "Client previously rejected this shipment",
    zh_hk: "此客戶曾拒收，無法重新指派",
    zh_cn: "此客户曾拒收，无法重新指派",
  },
  ALREADY_ASSIGNED: {
    status: 400,
    sys_code: "1600004",
    message: "Already has an active assignment",
    en: "Already has an active assignment",
    zh_hk: "已有未處理的指派",
    zh_cn: "已有未处理的指派",
  },
  NO_ASSIGNMENT_TO_CANCEL: {
    status: 400,
    sys_code: "1600005",
    message: "No active assignment to cancel",
    en: "No active assignment to cancel",
    zh_hk: "沒有可撤銷的指派",
    zh_cn: "没有可撤销的指派",
  },
  ALREADY_REJECTED_BY_CLIENT: {
    status: 400,
    sys_code: "1600006",
    message: "Already rejected by client",
    en: "Already rejected by client",
    zh_hk: "客戶已拒收",
    zh_cn: "客户已拒收",
  },
  ALREADY_ACCEPTED_BY_CLIENT: {
    status: 400,
    sys_code: "1600007",
    message: "Already accepted by client",
    en: "Already accepted by client",
    zh_hk: "客戶已接受",
    zh_cn: "客户已接受",
  },
  REJECT_NOTE_REQUIRED: {
    status: 400,
    sys_code: "1600008",
    message: "Reject note is required when reason is 'other'",
    en: "Reject note is required when reason is 'other'",
    zh_hk: "原因為「其他」時必須填備註",
    zh_cn: "原因为「其他」时必须填备注",
  },
  SHIPMENT_TYPE_FIXED_FOR_CS_ASSIGNED: {
    status: 400,
    sys_code: "1600009",
    message: "CS-assigned shipments must be consolidated",
    en: "CS-assigned shipments must be consolidated",
    zh_hk: "CS 指派的貨物只可選合併寄送",
    zh_cn: "CS 指派的货物只可选合并寄送",
  },
  CANNOT_DISPOSE_NON_PENDING: {
    status: 400,
    sys_code: "1600010",
    message: "Only pending_assignment unclaimed can be disposed",
    en: "Only pending_assignment unclaimed can be disposed",
    zh_hk: "只有 pending_assignment 狀態可處置",
    zh_cn: "只有 pending_assignment 状态可处置",
  },
};
