// Phase 3 — wallet errors.
// sys_code prefix 1300xxx — reusing the "BILL" slot from error-list.ts since
// v1 wallet replaces the legacy bills module (review.md §1.10).
export const WALLET_ERROR = {
  AMOUNT_TOO_LOW: {
    status: 400,
    sys_code: "1300001",
    message: "Topup amount below minimum",
    zh_hk: "儲值金額低於最低限額",
    zh_cn: "储值金额低于最低限额",
    en: "Topup amount below minimum",
  },
  INVALID_ADJUSTMENT_AMOUNT: {
    status: 400,
    sys_code: "1300002",
    message: "Adjustment amount cannot be zero",
    zh_hk: "調整金額不可為 0",
    zh_cn: "调整金额不可为 0",
    en: "Adjustment amount cannot be zero",
  },
  TOPUP_REQUEST_NOT_FOUND: {
    status: 404,
    sys_code: "1300003",
    message: "Topup request not found",
    zh_hk: "找不到此儲值申請",
    zh_cn: "找不到此储值申请",
    en: "Topup request not found",
  },
  TOPUP_ALREADY_PROCESSED: {
    status: 409,
    sys_code: "1300004",
    message: "Topup request already processed",
    zh_hk: "此儲值申請已處理",
    zh_cn: "此储值申请已处理",
    en: "Topup request already processed",
  },
  FILE_TOO_LARGE: {
    status: 400,
    sys_code: "1300005",
    message: "Uploaded file exceeds maximum size",
    zh_hk: "檔案超過最大限制",
    zh_cn: "档案超过最大限制",
    en: "Uploaded file exceeds maximum size",
  },
  FILE_TYPE_NOT_ALLOWED: {
    status: 400,
    sys_code: "1300006",
    message: "File type not allowed",
    zh_hk: "不允許的檔案類型",
    zh_cn: "不允许的档案类型",
    en: "File type not allowed",
  },
  PROOF_FILE_REQUIRED: {
    status: 400,
    sys_code: "1300007",
    message: "Transfer proof file is required",
    zh_hk: "請上傳匯款證明",
    zh_cn: "请上传汇款证明",
    en: "Transfer proof file is required",
  },
  PROOF_FILE_FORBIDDEN: {
    status: 403,
    sys_code: "1300008",
    message: "You do not have permission to access this file",
    zh_hk: "您無權存取此檔案",
    zh_cn: "您无权存取此档案",
    en: "You do not have permission to access this file",
  },
  REJECT_REASON_REQUIRED: {
    status: 400,
    sys_code: "1300009",
    message: "reject_reason is required",
    zh_hk: "請填寫駁回原因",
    zh_cn: "请填写驳回原因",
    en: "reject_reason is required",
  },
  WALLET_TRANSACTION_FAILED: {
    status: 500,
    sys_code: "1300010",
    message: "Wallet transaction failed",
    zh_hk: "錢包異動失敗",
    zh_cn: "钱包异动失败",
    en: "Wallet transaction failed",
  },
};
