export const INBOUND = {
  STATUS: {
    PENDING: "pending",
    RECEIVED: "received",
    SCHEDULED: "scheduled",
    OUTBOUNDING: "outbounding",
    OUTBOUNDED: "outbounded",
    CANCELLED: "cancelled",
  },
};

export const INBOUND_WORKFLOW: {
  [key: string]: any;
} = {
  [INBOUND.STATUS.RECEIVED]: [INBOUND.STATUS.PENDING],
  [INBOUND.STATUS.SCHEDULED]: [INBOUND.STATUS.RECEIVED],
  [INBOUND.STATUS.OUTBOUNDING]: [INBOUND.STATUS.SCHEDULED],
  [INBOUND.STATUS.OUTBOUNDED]: [
    INBOUND.STATUS.SCHEDULED,
    INBOUND.STATUS.OUTBOUNDING,
  ],
  [INBOUND.STATUS.CANCELLED]: [INBOUND.STATUS.PENDING],
};
